### ISSUE TITLE
ER: Further Import Validations

### ISSUE THREAD

**Issue by ersantosnet** [GoogleCloudPlatform/oracle-database-assessment#117]
### Enhancement Request Details

As a end user I want to make sure the following rules are enforced by the import utility. So, If I miss anything handling the set of files the import utility would let me know it.

- Make sure ALL *log files are from the same Script version. For instance, we had a case in which the user was trying to import ALL 2.0.4 logs, however, in the middle he had some old 2.0.3. 
- Make sure there are not 11.2 or 11.1 database versions being imported along with other database versions. OP utility cannot handle those imports today using -consolidatedataframes. If that happens we should stop processing and throw a message saying this is not supported and recommend the usage of a flag to filter database versions(which does not exists today). For example: -filterbydbversion "12.1,12.2,18.0,19.1"

**Comment by ersantosnet** [comment]
We can recommend the same strategy for whenever multiple versions are in the same folder by: -filterbysqlversion "2.0.4"

**Comment by divyapandian5** [comment]
Hi @ersantosnet  Based on the above strategy should we wait till filterbydbversion / filterbysqlversion implemented?
