### ISSUE TITLE
BUG: Too many values in row starting at position: 30863. Found 10 column(s) while expected 9.

### ISSUE THREAD

**Issue by smpawar** [GoogleCloudPlatform/oracle-database-assessment#135]
### Description

Getting this error for few tables:

dbfeatures"
 because of the error "400 Error while reading data, error message: Too many values in row starting at position: 30863. Found 10 column(s) while expected 9.".

Issue doesn't happen when using the fromdataframe flag. 

### Priority

priority:1

### What oracle database version are you seeing the problem on?

12c and above

**Comment by cofin** [comment]
This has been addressed in a recent push.  If we see a new one, let's open a new issue with info on the file that has the problem.
