### ISSUE TITLE
DOC: Review collector directory mention in the README.txt

### ISSUE THREAD

**Issue by smpawar** [GoogleCloudPlatform/oracle-database-assessment#219]
### Documentation change request Details?

In blob/main/scripts/collector/oracle/README.txt this is the line:

    a) Unzip the install archive. A "collector" subdirectory will be created.

When I download from https://googlecloudplatform.github.io/oracle-database-assessment/ it has below files:

drwxr-xr-x@ 17 user  primarygroup    544 Jan 27 09:45 sql
-rwxr-xr-x@  1 user  primarygroup   7206 Jan 27 09:45 collect-data.sh
-rw-r--r--@  1 user  primarygroup     68 Jan 27 09:45 VERSION.txt
-rw-r--r--@  1 user  primarygroup   5137 Jan 27 09:45 README.txt
-rw-r--r--@  1 user  primarygroup  11358 Jan 27 09:45 LICENSE

### Version

None

### What oracle database version are you seeing the problem on?

None

### Which sql script version ?

None

**Comment by cofin** [comment]
Can you please open a PR and submit the fix for this?

**Comment by smpawar** [comment]
Created https://github.com/GoogleCloudPlatform/oracle-database-assessment/pull/220
