### ISSUE TITLE
DOC: Add UseDiagnostics to the documentation

### ISSUE THREAD

**Issue by smpawar** [GoogleCloudPlatform/oracle-database-assessment#227]
### Documentation change request Details?

Modify this instruction.
    a) Execute ./collect-data.sh, passing a database connection string as the only parameter:

        ./collect-data.sh 'username/password@//hostname.domain.com:1521/dbname.domain.com as sysdba'

### Version

None

### What oracle database version are you seeing the problem on?

12c and above

### Which sql script version ?

None

**Comment by wpuziewicz** [comment]
Fixed in #232
