### ISSUE TITLE
ER: Improve SQL Collection For AwrSnapDetails

### ISSUE THREAD

**Issue by ersantosnet** [GoogleCloudPlatform/oracle-database-assessment#65]
**From:** 
SELECT MIN(snap_id) min_snapid,
       MAX(snap_id) max_snapid
FROM   dba_hist_snapshot
WHERE  begin_interval_time > ( SYSDATE - 30 )
/

**To:**
SELECT MIN(snap_id) min_snapid,
       MAX(snap_id) max_snapid
FROM   dba_hist_snapshot
WHERE  begin_interval_time > ( SYSDATE - 30 )
and dbid = (select dbid from v$database)
/

Do further analysis on if is necessary to include the same where clause on other QUERIES.

**Comment by smancinijr** [comment]
Add min and max snap_id to opkeylog file/table and also based on the AWR interval in DBA_HIST_WR_CONTROL, calculate how much interval should exists and compare with how much is present in the DBA_HIST views. 
Target: Validate how much data is present in the AWR and how much this data is reliable.
