### ISSUE TITLE
ER: Configure Initial Views to Enable OP 3.0.1 Reporting

### ISSUE THREAD

**Issue by ersantosnet** [GoogleCloudPlatform/oracle-database-assessment#79]

**Comment by cofin** [comment]
I think this is at least partially resolved by @wpuziewicz work on #180 

This will now deploy the BigQuery views and execute the curl command to create the new report from the DataStudio template.

**Comment by wpuziewicz** [comment]
@ersantosnet Is this regarding creation of the currently define views/tables , or a new set of views/tables?

**Comment by cofin** [comment]
closed by script automations from @wpuziewicz
