### ISSUE TITLE
BUG: ModuleNotFoundError: No module named 'google

### ISSUE THREAD

**Issue by smpawar** [GoogleCloudPlatform/oracle-database-assessment#82]
Issue : When trying to run Step 2 from the database server i get the below error

```
python optimusprime.py -dataset newdatasetORexistingdataset -collectionid 02032200303 -fileslocation //home/oracle/users/smpawar/oracle-database-assessment-output -projectname my-awesome-gcp-project
Traceback (most recent call last):
  File "optimusprime.py", line 25, in <module>
    import set_client_info
  File "/home/oracle/users/smpawar/oracle-database-assessment/db_assessment/set_client_info.py", line 16, in <module>
    from google.api_core import client_info as http_client_info
ModuleNotFoundError: No module named 'google'
```

**Comment by smpawar** [comment]
added below modules in the venv to get past ModuleNotFoundError errors:
pip3 install --upgrade google-api-python-client
pip3 install --upgrade google-cloud
pip3 install --upgrade google-cloud-bigquery
pip3 install --upgrade google-cloud-storage
pip3 install --upgrade pandas

Will fix the documentation via a commit

**Comment by cofin** [comment]
This has been updated in the latest releases.  Closing this.
