### ISSUE TITLE
BUG:  cosmetics in the optimusprime.py output

### ISSUE THREAD

**Issue by ferhatsengonul** [GoogleCloudPlatform/oracle-database-assessment#97]
### Description

in the output of opotimusprime.py , Successfully is misspelled. :) Sorry , I am O-C.

Sucessfully created filename :  has to be successfully

### Version

1.0.3 (Edge)

### Priority

priority:3

### What oracle database version are you seeing the problem on?

All

### Relevant log output

```shell
Sucessfully created filename :
```

**Comment by cofin** [comment]
Resolved by #199
