### ISSUE TITLE
ER: create a optimusprime.py log file which also summaries have many tables are loaded and whether there is an error or not

### ISSUE THREAD

**Issue by ferhatsengonul** [GoogleCloudPlatform/oracle-database-assessment#98]
### Enhancement Request Details

As a end user I want to  see a summary of the optimusprime.py output in a log file.  i solve it via directing the output to a log file and then grepping the FAILED keyword.

### What oracle database version are you seeing the problem on?

All

**Comment by cofin** [comment]
closed by #125
